{"additions": 1, "auther_ref": "py3-sqlalchemy-1.3.10", "auther_sha": "da304ae34520ae28c42e9b9301e22a0e4a4443bb", "author": "cms-sw", "body": "This shoudl fix the O2O unit test failing in Py3 IB. This happened as we moved to sqlalchemy 1.3.10 which had some changes breaking python3 ", "branch": "IB/CMSSW_11_0_X/master", "changed_files": 2, "comments": 3, "commits": 1, "created_at": "1572987188", "deletions": 14, "labels": ["comparison-pending", "externals-pending", "orp-pending", "pending-signatures", "tests-started"], "number": 5334, "release-notes": [], "review_comments": 0, "state": "open", "title": "patch sqlalchemy 1.3.10 for python3", "updated_at": "1572987228", "user": "smuzaffar"}