{"additions": 35, "auther_ref": "py3-sqlalchemy-1.3.10", "auther_sha": "e7322933f3fd4240d094a638d6382564c6c40295", "author": "cms-sw", "body": "This shoudl fix the O2O unit test failing in Py3 IB. This happened as we moved to sqlalchemy 1.3.10 which had some changes breaking python3 ", "branch": "IB/CMSSW_11_0_X/master", "changed_files": 3, "comments": 6, "commits": 2, "created_at": "1572987188", "deletions": 14, "labels": ["comparison-pending", "externals-pending", "orp-pending", "pending-signatures", "tests-pending"], "number": 5334, "release-notes": [], "review_comments": 0, "state": "open", "title": "patch sqlalchemy 1.3.10 for python3", "updated_at": "1572987465", "user": "smuzaffar"}